--初始状态
insert into lhmbills 
       (FID, FUUID, FBILL, FBILLTYPE, FTIME, 
       FSYSTEMCODE, FWAREHOUSECODE, FMAINDEPTCODE, FREMARK,
       FTOWAREHOUSECODE, FTODEPTCODE, FCUSTOMERCODE, FCUSTOMERNAME, FCUSTOMERADDR,
       FISPALLETINPUT, FPLANARRIVALDATE, FINVALIDDATE, FSUBBIZTYPE,
       FFROMWAREHOUSECODE, FFROMDEPTCODE, FFROMSUPPLIERCODE, FFROMSUPPLIERNAME, FFROMSUPPLIERCONTACT,
       FWMSBILL)
values (0, '1234', '1234', '1234', to_date('08-08-2017', 'dd-mm-yyyy'), 
       '20170808', '20170808', '20170808', '20170808',
       '20170808', '20170808', '20170808', '20170808', '20170808',
       '1', to_date('08-08-2017', 'dd-mm-yyyy'), to_date('08-08-2017', 'dd-mm-yyyy'), 2345,
       '24532', '234526', '3456346', '23452435', '26236', 
       '23626262');


--通用状态
insert into lhmbills 
       (FID , FUUID, FBILL, FBILLTYPE, FTIME, 
       FSYSTEMCODE, FWAREHOUSECODE, FMAINDEPTCODE, FREMARK,
       FTOWAREHOUSECODE, FTODEPTCODE, FCUSTOMERCODE, FCUSTOMERNAME, FCUSTOMERADDR,
       FISPALLETINPUT, FPLANARRIVALDATE, FINVALIDDATE, FSUBBIZTYPE,
       FFROMWAREHOUSECODE, FFROMDEPTCODE, FFROMSUPPLIERCODE, FFROMSUPPLIERNAME, FFROMSUPPLIERCONTACT,
       FWMSBILL)
values (NVL(( select max(lhmbills.fid)+1 from lhmbills),0) , '1234', '1234', '1234', sysdate, 
       '20170808', '20170808', '20170808', '20170808',
       '20170808', '20170808', '20170808', '20170808', '20170808',
       '1', to_date('08-08-2017', 'dd-mm-yyyy'), to_date('08-08-2017', 'dd-mm-yyyy'), 2345,
       '24532', '234526', '3456346', '23452435', '26236', 
       '23626262');


--入库单据：HMBillIn
insert into lhmbills 
        (FID , FUUID, FBILL, FBILLTYPE, FTIME, 
        FSYSTEMCODE, FWAREHOUSECODE, FMAINDEPTCODE, FREMARK,
        FTOWAREHOUSECODE, FTODEPTCODE, FCUSTOMERCODE, FCUSTOMERNAME, FCUSTOMERADDR,
        FPLANARRIVALDATE, FINVALIDDATE, FSUBBIZTYPE,
        FISPALLETINPUT, FFROMWAREHOUSECODE, FFROMDEPTCODE, FFROMSUPPLIERCODE, FFROMSUPPLIERNAME, FFROMSUPPLIERCONTACT,
        FWMSBILL)
values (NVL(( select max(lhmbills.fid)+1 from lhmbills),0) , #FUUID#, #FBILL#, #FBILLTYPE#, sysdate, 
        #FSYSTEMCODE#, #FWAREHOUSECODE#, #FMAINDEPTCODE#, #FREMARK#,
        '', '', '', '', '',
        #FPLANARRIVALDATE#, #FINVALIDDATE#, #FSUBBIZTYPE#,
        #FISPALLETINPUT#,#FFROMWAREHOUSECODE#, #FFROMDEPTCODE#, #FROMSUPPLIERCODE#, #FFROMSUPPLIERNAME#, #FFROMSUPPLIERCONTACT#,
        #FWMSBILL#);
       

--出库单据：HMBillOut
insert into lhmbills 
        (FID , FUUID, FBILL, FBILLTYPE, FTIME, 
        FSYSTEMCODE, FWAREHOUSECODE, FMAINDEPTCODE, FREMARK,
        FTOWAREHOUSECODE, FTODEPTCODE, FCUSTOMERCODE, FCUSTOMERNAME, FCUSTOMERADDR,
        FPLANARRIVALDATE, FINVALIDDATE, FSUBBIZTYPE,
        FISPALLETINPUT,FFROMWAREHOUSECODE, FFROMDEPTCODE, FFROMSUPPLIERCODE, FFROMSUPPLIERNAME, FFROMSUPPLIERCONTACT,
        FWMSBILL)
values (NVL(( select max(lhmbills.fid)+1 from lhmbills),0) , #FUUID#, #FBILL#, #FBILLTYPE#, sysdate, 
        #FSYSTEMCODE#, #FWAREHOUSECODE#, #FMAINDEPTCODE#, #FREMARK#,
        #FTOWAREHOUSECODE#, #FTODEPTCODE#, #FCUSTOMERCODE#, #FCUSTOMERNAME#, #FCUSTOMERADDR#,
        '', '', '',
        '', '', '', '', '', '', 
        #FWMSBILL#);